source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }



# Specify your gem's dependencies in ruby.gemspec
gemspec

group :development do
  gem 'rubocop-rspec', '1.3.1'
  gem 'rubocop', '0.35.1'
end